version: '3.7'

services:
  proj1:
    container_name: proj1
#    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    networks:
      - network1

networks:
  network1:
    name: network1
#     Сообщает о том, что сеть nginx_net находится не в этом контейнере.