version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
      - data:/var/docker/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: forjetx@gmail.com

  stat:
    container_name: internationaltrashaward.org
    image: alextael/trashv17
    expose:
      - "3000"
    environment:
      VIRTUAL_HOST: internationaltrashaward.org
      LETSENCRYPT_HOST: internationaltrashaward.org
    volumes:
      - data:/var/docker/data/stat

  mongodb:
    image: mongo:7.0.5
    container_name: my-mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
      - '.private/mongo_data:/var/lib/mongodb'
    ports:
      - 27017:27017

volumes:
  data:
  mongodb_data: