version: '3.7'

services:
  internationaltrashaward:
    container_name: internationaltrashaward
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      nginx_net:

networks:
  nginx_net:
    external: true
#     Сообщает о том, что сеть nginx_net находится не в этом контейнере.