version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - network1
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:5000

networks:
  network1:
    name: network1